logging.level.org.springframework.web=DEBUG
logging.level.in.amulya=DEBUG
spring.application.name=dingdong
spring.data.mongodb.uri=${MONGODB_URI}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

jwt.secret.key=${JWT_SECRET}

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}
